# Generated by Django 5.1 on 2024-08-18 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.course'),
        ),
    ]
