# Generated by Django 5.1 on 2024-08-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_tutorial_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
