# Generated by Django 5.1 on 2024-08-18 03:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_tutorial_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
