# Generated by Django 5.1 on 2024-08-18 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_tutorial_tutorial_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=255)),
                ('dep_description', models.TextField(blank=True, null=True)),
                ('dep_image', models.ImageField(blank=True, null=True, upload_to='dep_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_desc',
            new_name='course_description',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=121313, on_delete=django.db.models.deletion.CASCADE, to='tutorials.department'),
            preserve_default=False,
        ),
    ]
