# Generated by Django 5.1 on 2024-08-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_rename_course_desc_course_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
