# Generated by Django 5.1 on 2024-08-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_course_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
