# Generated by Django 5.1 on 2024-08-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_author_tutorial_author_course_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
